name: GitHub Container Registry
on: [push]
jobs:
  build-publish-docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - name: login ghcr
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/flaskapp:latest
